### ISSUE TITLE
app & server screenshots?

### ISSUE THREAD

**Issue by dazzaji** [dcalacci/breakout#1]
Dan - sorry I timed out today before we could update/demo each other on recent progress.  

Only if it's easy - could you please share a few screen shots of how the app looks from a user perspective and maybe the server admin or config screen (if any)?

**Comment by dcalacci** [comment]
ah, just saw this now, dazza. 

work is still early on this, it took a lot of effort to get data moving between hangouts and a private server, so there's very little being done. 

right now what is being worked on is the data format for sending data between the UI and the back-end, and the architecture for processing that data (like jason and I have done previously). 

hopefully will have more to share this friday!

**Comment by dazzaji** [comment]
thanks!
