### ISSUE TITLE
What does `remove_talking_history_repeats` do?

### ISSUE THREAD

**Issue by ryannealmes** [dcalacci/breakout#55]
The following method [`remove_talking_history_repeats`](https://github.com/HumanDynamics/breakout/blob/master/server/my_hooks.js#L23), I would imagine removes duplicate entries in the `talking_history` collection. 

I can't actually see it removing/deleting or preventing inserts. Maybe I am just misunderstanding something?

**Comment by dcalacci** [comment]
this was fixed in a refactor. 

``` javascript
                if (matches.length == 0) {
                    winston.log("info", "Inserting new talking history data, not a repeat...");
                    winston.log("info", hook.data);
                    next();
                } else {
                    winston.log("info", "Tried to insert repeat talking history data! Nuh-Uh");
                    next();
                }
```

the `else` case here shouldn't have the `next();` continuation in it. If this continuation is gone, then the data never moves past this hook, stopping any repeated talking events from entering the database.
