### ISSUE TITLE
Google Hangouts API deprecated

### ISSUE THREAD

**Issue by patcon** [dcalacci/breakout#60]
https://9to5google.com/2017/01/06/google-hangouts-api-dead-april-25th/

Might it be worth putting this prominently in the README? If I'm understanding correctly, this won't work soon :(

This might be convertible into a Jitsi Meet plugin though.

**Comment by dcalacci** [comment]
Hey! Yes, this has been deprecated. We have our own RTC client/server, and plugins that work with any MediaStream interface now though! 

Fair warning that these are still in early alpha, with little documentation

rtc client: https://github.com/HumanDynamics/rhythm-rtc
speech plugin: https://github.com/dcalacci/sibilant

**Comment by dcalacci** [comment]
+1 for adding to the readme though
